export type MenuItem = { name: string; price: string };
export type MenuCategory = { title: string; items: MenuItem[]; image?: string };

const img = (q: string) =>
  `https://images.unsplash.com/${q}?auto=format&fit=crop&w=400&q=80`;

export const menu: MenuCategory[] = [
  {
    title: "South Indian Snacks",
    image: img("photo-1668236543090-82eba5ee5976"),
    items: [
      { name: "Idli Sambar", price: "100" },
      { name: "Idli Sambar (Single)", price: "55" },
      { name: "Idli Wada", price: "110" },
      { name: "Medu Wada", price: "115" },
      { name: "Medu Wada (Single)", price: "65" },
      { name: "Sada Dosa", price: "110" },
      { name: "Mix Wada", price: "120" },
      { name: "Butter Sada Dosa", price: "120" },
      { name: "Cheese Sada Dosa", price: "135" },
      { name: "Masala Dosa", price: "125" },
      { name: "Mysore Masala Dosa", price: "140" },
      { name: "Mysore Sada Dosa", price: "130" },
      { name: "Paper Sada Dosa", price: "190" },
      { name: "Paper Masala", price: "220" },
      { name: "Cut Masala Dosa", price: "145" },
      { name: "Ghee Sada Dosa", price: "135" },
      { name: "Plain Uttapam", price: "120" },
      { name: "Masala Uttapam", price: "160" },
      { name: "Cheese Uttapam", price: "160" },
      { name: "Onion/Tomato Uttapam", price: "155" },
      { name: "Rawa Sada Dosa", price: "125" },
      { name: "Onion Rawa Dosa", price: "140" },
      { name: "Rawa Masala Dosa", price: "155" },
      { name: "Aloo Parantha", price: "145" },
    ],
  },
  {
    title: "Fasting Snacks",
    image: img("photo-1626074353765-517a681e40be"),
    items: [
      { name: "Sabudana Khichidi", price: "125" },
      { name: "Sabudana Wada", price: "125" },
      { name: "French Fries", price: "125" },
    ],
  },
  {
    title: "Extras",
    items: [
      { name: "Extra Cheese", price: "35" },
      { name: "Extra Butter", price: "35" },
      { name: "Extra Pav", price: "7" },
      { name: "Butter Pav", price: "10" },
      { name: "Extra Cup", price: "5" },
      { name: "Extra Sambhar", price: "5" },
    ],
  },
  {
    title: "House Specials",
    image: img("photo-1606491956689-2ea866880c84"),
    items: [
      { name: "Missal Pav", price: "110" },
      { name: "Dahi Missal Pav", price: "135" },
      { name: "Upma (Till 10 Am)", price: "85" },
      { name: "Poha (Till 10 Am)", price: "85" },
      { name: "Batata Wada / Sambar", price: "85" },
      { name: "Batata Wada-Pav (Single)", price: "45" },
      { name: "Vithal Batata Wada", price: "135" },
      { name: "Mix Pakoda / Onion Pakoda", price: "115" },
      { name: "Paneer Pakoda", price: "230" },
      { name: "Tomato Omlette", price: "185" },
      { name: "Pav Bhaji", price: "145" },
      { name: "Cheese Pav Bhaji", price: "170" },
    ],
  },
  {
    title: "Sandwiches (Grilled / Plain)",
    image: img("photo-1528735602780-2552fd46c7af"),
    items: [
      { name: "Bread Butter", price: "95" },
      { name: "Jam Bread", price: "95" },
      { name: "Bread Butter Jam", price: "110" },
      { name: "Toast Butter", price: "115" },
      { name: "Veg Sandwich", price: "120" },
      { name: "Veg Cheese Sandwich", price: "135" },
      { name: "Cheese Sandwich", price: "125" },
      { name: "Cheese Toast Sandwich", price: "160" },
      { name: "Cheese Grilled Sandwich", price: "160" },
      { name: "Cheese Chilly Grilled Sandwich", price: "185" },
      { name: "Veg Cheese Toast Sandwich", price: "180" },
      { name: "Veg Grill Sandwich", price: "170" },
      { name: "Veg Cheese Grill Sandwich", price: "210" },
    ],
  },
  {
    title: "Hot & Cold Beverages",
    image: img("photo-1541167760496-1628856ab772"),
    items: [
      { name: "Tea", price: "30" },
      { name: "Green Tea / Lemon Tea", price: "35" },
      { name: "South Indian Coffee", price: "40" },
      { name: "Ness Coffee", price: "45" },
      { name: "Cold Coffee", price: "135" },
      { name: "Solkadhi", price: "60" },
      { name: "Fresh Lime Water", price: "50" },
      { name: "Fresh Lime Soda", price: "60" },
      { name: "Plain Chass", price: "50" },
      { name: "Masala Chass", price: "55" },
      { name: "Lassi Sweet / Salted", price: "95" },
      { name: "Hot Milk", price: "60" },
    ],
  },
  {
    title: "Raita",
    items: [
      { name: "Veg Raita", price: "200" },
      { name: "Boondi Raita", price: "210" },
      { name: "Plain Curd / Portion", price: "55 / 110" },
    ],
  },
  {
    title: "Salad",
    items: [
      { name: "Green Salad", price: "135" },
      { name: "Roasted Papad", price: "35" },
      { name: "Fry Papad", price: "45" },
      { name: "Masala Papad", price: "75" },
    ],
  },
  {
    title: "Main Course",
    image: img("photo-1585937421612-70a008356fbe"),
    items: [
      { name: "Dal Fry", price: "180" },
      { name: "Dal Tadka", price: "195" },
      { name: "Veg Kadai F/H", price: "760 / 380" },
      { name: "Veg Handi F/H", price: "760 / 380" },
      { name: "Chole Masala", price: "240" },
      { name: "Besan (Pitla)", price: "240" },
      { name: "Green Peas Masala", price: "250" },
      { name: "Paneer Bhurji", price: "310" },
      { name: "Aloo Mutter", price: "240" },
      { name: "Paneer Masala", price: "310" },
      { name: "Paneer Butter Masala", price: "310" },
      { name: "Plain Palak", price: "230" },
      { name: "Methi Mutter Malai", price: "290" },
      { name: "Baigan Masala", price: "240" },
      { name: "Veg Makkhanwala", price: "310" },
      { name: "Kaju Masala", price: "310" },
      { name: "Kaju Paneer Masala", price: "330" },
      { name: "Aloo Jeera", price: "240" },
      { name: "Paneer Makhani", price: "310" },
      { name: "Paneer Tikka Masala", price: "340" },
      { name: "Paneer Mutter", price: "340" },
      { name: "Paneer Chingari", price: "320" },
      { name: "Veg Makhani", price: "310" },
      { name: "Mushroom Masala", price: "310" },
      { name: "Mix Veg", price: "295" },
      { name: "Veg Kolhapuri", price: "320" },
      { name: "Paneer Kadai F/H", price: "790 / 410" },
      { name: "Paneer Handi F/H", price: "790 / 410" },
      { name: "Lasooni Palak", price: "240" },
      { name: "Palak Paneer", price: "310" },
    ],
  },
  {
    title: "Rice & Noodles",
    image: img("photo-1596797038530-2c107229654b"),
    items: [
      { name: "Steam Rice F/H", price: "140 / 95" },
      { name: "Jeera Rice F/H", price: "165 / 115" },
      { name: "Veg Pulao", price: "240" },
      { name: "Veg Biryani", price: "310" },
      { name: "Curd Rice", price: "210" },
      { name: "Dal Khichdi", price: "250" },
    ],
  },
  {
    title: "Meals (Thali)",
    image: img("photo-1567337710282-00832b415979"),
    items: [
      { name: "Pital Thali", price: "245" },
      { name: "Maharashtrian Thali", price: "280" },
      { name: "Satara Thali", price: "310" },
      { name: "Executive Thali", price: "320" },
      { name: "Deluxe Thali", price: "340" },
    ],
  },
  {
    title: "Roti / Naan",
    image: img("photo-1626100134240-19f5b17ef82f"),
    items: [
      { name: "Tandoor Roti", price: "30" },
      { name: "Butter Tandoor Roti", price: "40" },
      { name: "Wheat Roti", price: "40" },
      { name: "Wheat Butter Roti", price: "45" },
      { name: "Plain Naan", price: "55" },
      { name: "Butter Naan", price: "65" },
      { name: "Garlic Naan", price: "90" },
      { name: "Chapati", price: "30" },
      { name: "Bhakri", price: "40" },
      { name: "Plain Parantha", price: "50" },
      { name: "Butter Parantha", price: "70" },
    ],
  },
  {
    title: "Desserts",
    image: img("photo-1587314168485-3236d6710814"),
    items: [
      { name: "Gulab Jamun (3 Piece)", price: "110" },
      { name: "Moong Dal Halwa", price: "120" },
    ],
  },
  {
    title: "Maharashtrian Special",
    image: img("photo-1631452180519-c014fe946bc7"),
    items: [
      { name: "Akkha Masoor", price: "240" },
      { name: "Bhendi Masala", price: "245" },
      { name: "Matki Masala", price: "250" },
      { name: "Matki Fry", price: "240" },
      { name: "Baigan Masala", price: "240" },
      { name: "Baigan Bharta", price: "250" },
      { name: "Besan Pithla", price: "240" },
      { name: "Methi Pithla", price: "260" },
      { name: "Shengdanyacha Mahdya", price: "250" },
    ],
  },
  {
    title: "Combo",
    image: img("photo-1601050690597-df0568f70950"),
    items: [
      { name: "Curd Rice + Chass + Raita", price: "255" },
      { name: "Veg Pulao + Chass + Raita + Roasted Papad", price: "295" },
      { name: "Dal Khichadi + Chass + Raita + Roasted Papad", price: "275" },
      { name: "Veg Biryani + Chass + Raita + Roasted Papad", price: "330" },
    ],
  },
];
